Replace some text() with column() and fix missing textual SQL marker
[2019-10-17 19:31:05,630] {{taskinstance.py:1051}} ERROR - Textual SQL expression '"glue"."sfoi"."account"' should be explicitly declared as text('"glue"."sfoi"."account"')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/salesforce_import_extras/common_functions.py", line 69, in ctas_to_snowflake
    [text("*")], from_obj=f'"glue"."{sfdc_instance}"."{sobject_name}"'
  File "<string>", line 2, in __init__
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 128, in warned
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/selectable.py", line 2965, in __init__
    _interpret_as_from(f) for f in util.to_list(from_obj)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 365, in __init__
    self._list = unique_list(d)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 759, in unique_list
    return [x for x in seq if x not in seen and not seen_add(x)]
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 759, in <listcomp>
    return [x for x in seq if x not in seen and not seen_add(x)]
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/selectable.py", line 2965, in <genexpr>
    _interpret_as_from(f) for f in util.to_list(from_obj)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/selectable.py", line 59, in _interpret_as_from
    _no_text_coercion(element)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 4563, in _no_text_coercion
    "extra": "%s " % extra if extra else "",
sqlalchemy.exc.ArgumentError: Textual SQL expression '"glue"."sfoi"."account"' should be explicitly declared as text('"glue"."sfoi"."account"')