Fix misquoted strings
[2019-10-17 19:46:30,168] {{taskinstance.py:1051}} ERROR - {'message': "line 3:24: Column 'sfoi' cannot be resolved", 'errorCode': 47, 'errorName': 'COLUMN_NOT_FOUND', 'errorType': 'USER_ERROR', 'errorLocation': {'lineNumber': 3, 'columnNumber': 24}, 'failureInfo': {'type': 'io.prestosql.spi.PrestoException', 'message': "line 3:24: Column 'sfoi' cannot be resolved", 'suppressed': [], 'stack': ['io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:63)', 'io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:58)', 'io.prestosql.sql.analyzer.SemanticExceptions.missingAttributeException(SemanticExceptions.java:34)', 'io.prestosql.sql.analyzer.Scope.lambda$resolveField$0(Scope.java:104)', 'java.base/java.util.Optional.orElseThrow(Optional.java:408)', 'io.prestosql.sql.analyzer.Scope.resolveField(Scope.java:104)', 'io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.visitIdentifier(ExpressionAnalyzer.java:399)', 'io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.visitIdentifier(ExpressionAnalyzer.java:315)', 'io.prestosql.sql.tree.Identifier.accept(Identifier.java:72)', 'io.prestosql.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)', 'io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:338)', 'io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.getOperator(ExpressionAnalyzer.java:1317)', 'io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.visitComparisonExpression(ExpressionAnalyzer.java:489)', 'io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.visitComparisonExpression(ExpressionAnalyzer.java:315)', 'io.prestosql.sql.tree.ComparisonExpression.accept(ComparisonExpression.java:71)', 'io.prestosql.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)', 'io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:338)', 'io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.coerceType(ExpressionAnalyzer.java:1350)', 'io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.visitLogicalBinaryExpression(ExpressionAnalyzer.java:479)', 'io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.visitLogicalBinaryExpression(ExpressionAnalyzer.java:315)', 'io.prestosql.sql.tree.LogicalBinaryExpression.accept(LogicalBinaryExpression.java:88)', 'io.prestosql.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)', 'io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:338)', 'io.prestosql.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:275)', 'io.prestosql.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:1535)', 'io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeExpression(StatementAnalyzer.java:2093)', 'io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeWhere(StatementAnalyzer.java:1940)', 'io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.lambda$visitQuerySpecification$16(StatementAnalyzer.java:1090)', 'java.base/java.util.Optional.ifPresent(Optional.java:183)', 'io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1090)', 'io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:268)', 'io.prestosql.sql.tree.QuerySpecification.accept(QuerySpecification.java:144)', 'io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)', 'io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:283)', 'io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:293)', 'io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:784)', 'io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:268)', 'io.prestosql.sql.tree.Query.accept(Query.java:107)', 'io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)', 'io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:283)', 'io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:260)', 'io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:76)', 'io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:68)', 'io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:216)', 'io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:176)', 'io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:93)', 'io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:711)', 'io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:118)', 'com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)', 'com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)', 'com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)', 'java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)', 'java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)', 'java.base/java.lang.Thread.run(Thread.java:834)'], 'errorLocation': {'lineNumber': 3, 'columnNumber': 24}}}
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/salesforce_import_extras/common_functions.py", line 99, in ctas_to_snowflake
    .where(column("table_name") == text(sobject_name))
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1272, in _execute_context
    result = context.get_result_proxy()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 1126, in get_result_proxy
    return result.ResultProxy(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/result.py", line 720, in __init__
    self._init_metadata()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/result.py", line 739, in _init_metadata
    cursor_description = self._cursor_description()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/result.py", line 865, in _cursor_description
    return self._saved_cursor.description
  File "/usr/local/lib/python3.7/site-packages/pyhive/presto.py", line 161, in description
    lambda: self._columns is None and
  File "/usr/local/lib/python3.7/site-packages/pyhive/common.py", line 45, in _fetch_while
    self._fetch_more()
  File "/usr/local/lib/python3.7/site-packages/pyhive/presto.py", line 243, in _fetch_more
    self._process_response(self._requests_session.get(self._nextUri, **self._requests_kwargs))
  File "/usr/local/lib/python3.7/site-packages/pyhive/presto.py", line 282, in _process_response
    raise DatabaseError(response_json['error'])
pyhive.exc.DatabaseError: {'message': "line 3:24: Column 'sfoi' cannot be resolved", 'errorCode': 47, 'errorName': 'COLUMN_NOT_FOUND', 'errorType': 'USER_ERROR', 'errorLocation': {'lineNumber': 3, 'columnNumber': 24}, 'failureInfo': {'type': 'io.prestosql.spi.PrestoException', 'message': "line 3:24: Column 'sfoi' cannot be resolved", 'suppressed': [], 'stack': ['io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:63)', 'io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:58)', 'io.prestosql.sql.analyzer.SemanticExceptions.missingAttributeException(SemanticExceptions.java:34)', 'io.prestosql.sql.analyzer.Scope.lambda$resolveField$0(Scope.java:104)', 'java.base/java.util.Optional.orElseThrow(Optional.java:408)', 'io.prestosql.sql.analyzer.Scope.resolveField(Scope.java:104)', 'io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.visitIdentifier(ExpressionAnalyzer.java:399)', 'io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.visitIdentifier(ExpressionAnalyzer.java:315)', 'io.prestosql.sql.tree.Identifier.accept(Identifier.java:72)', 'io.prestosql.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)', 'io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:338)', 'io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.getOperator(ExpressionAnalyzer.java:1317)', 'io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.visitComparisonExpression(ExpressionAnalyzer.java:489)', 'io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.visitComparisonExpression(ExpressionAnalyzer.java:315)', 'io.prestosql.sql.tree.ComparisonExpression.accept(ComparisonExpression.java:71)', 'io.prestosql.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)', 'io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:338)', 'io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.coerceType(ExpressionAnalyzer.java:1350)', 'io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.visitLogicalBinaryExpression(ExpressionAnalyzer.java:479)', 'io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.visitLogicalBinaryExpression(ExpressionAnalyzer.java:315)', 'io.prestosql.sql.tree.LogicalBinaryExpression.accept(LogicalBinaryExpression.java:88)', 'io.prestosql.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)', 'io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:338)', 'io.prestosql.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:275)', 'io.prestosql.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:1535)', 'io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeExpression(StatementAnalyzer.java:2093)', 'io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeWhere(StatementAnalyzer.java:1940)', 'io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.lambda$visitQuerySpecification$16(StatementAnalyzer.java:1090)', 'java.base/java.util.Optional.ifPresent(Optional.java:183)', 'io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1090)', 'io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:268)', 'io.prestosql.sql.tree.QuerySpecification.accept(QuerySpecification.java:144)', 'io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)', 'io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:283)', 'io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:293)', 'io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:784)', 'io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:268)', 'io.prestosql.sql.tree.Query.accept(Query.java:107)', 'io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)', 'io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:283)', 'io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:260)', 'io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:76)', 'io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:68)', 'io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:216)', 'io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:176)', 'io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:93)', 'io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:711)', 'io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:118)', 'com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)', 'com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)', 'com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)', 'java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)', 'java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)', 'java.base/java.lang.Thread.run(Thread.java:834)'], 'errorLocation': {'lineNumber': 3, 'columnNumber': 24}}}